/**
 * API SST
 * No description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.actividad
 */
export class Actividad { 
    idActividad: number;
    nombreActividad?: string;
    idTActividadA?: number;
    idFrecuenciaA?: number;
    idEvidenciaA?: number;
    idSistemaEvaluacion?: number;
    idIdoneidadInstructor?: number;
}
