/**
 * API SST
 * No description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.indicadorsg
 */
export class Indicadorsg { 
    idEstadoPlan: number;
    nombreIndicadorSG?: string;
    definicionIndicador?: string;
    comoMide?: string;
    interpretacionIndicador?: string;
    metaIndicador?: number;
    idFuenteInformacionI?: number;
    idFrecuenciaI?: number;
    idTipoIndicador?: number;
}
