/**
 * API SST
 * No description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.tipoactividad
 */
export class Tipoactividad { 
    idTActividad: number;
    nombreTActividad?: string;
    meta?: string;
    objetivo?: string;
}
